### GET /
GET https://livechat.thinhnw.site/


### GET /chat_rooms
GET https://livechat.thinhnw.site/chat_rooms


### CREATE A USER
POST https://livechat.thinhnw.site/auth/register
Accept: application/json

{
    "email": "johndoe@example.com",
    "password": "12345678"
}
