@API_URL = https://livechat.thinhnw.site
@authToken = {{tokenAPI.response.body.access_token}}
### GET /
GET {{API_URL}} 


### REGISTER, CREATE A USER
POST {{API_URL}}/auth/register
Accept: application/json

{
    "email": "johndoe@example.com",
    "password": "12345678"
}


### LOGIN
# @name tokenAPI
POST {{API_URL}}/auth/login
Accept: application/json

{
    "email": "johndoe@example.com",
    "password": "12345678"
}


### GET user_me
GET {{API_URL}}/auth/me 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}


### Create a chat room
POST {{API_URL}}/chat_rooms
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "New Group",
    "type": "group"
}


### Get user's chat rooms
GET {{API_URL}}/chat_rooms
Accept: application/json
Authorization: Bearer {{authToken}}