@API_URL = https://livechat.thinhnw.site
@authToken = {{tokenAPI.response.body.access_token}}
### GET /
GET {{API_URL}} 


### GET /chat_rooms
GET https://livechat.thinhnw.site/chat_rooms


### REGISTER, CREATE A USER
POST https://livechat.thinhnw.site/auth/register
Accept: application/json

{
    "email": "johndoe@example.com",
    "password": "12345678"
}


### LOGIN
# @name tokenAPI
POST {{API_URL}}/auth/login
Accept: application/json

{
    "email": "johndoe@example.com",
    "password": "12345678"
}


### GET user_me
GET {{API_URL}}/auth/me HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}
